### ISSUE TITLE
AttributeError When Running QCGPU Examples

### ISSUE THREAD

**Issue by BetaByter** [Qiskit/qiskit-qcgpu-provider#2]
Sorry for the double issue, GitHub had a bit of a fit!

When attempting to run any of the examples, I get the following attribute error:

`module 'qcgpu.backend' has no attribute  'create_context'
`
This happens when I call QCGPUProvider(), which calls create_context() on line 17 of _init_.py. I'm running Python 3.6.6 on a Linux machine, with Qiskit 0.6.1, Qiskit Aqua 0.3.0, pyopencl version 2018.2.1, and version 0.0.1 of this library.

Any idea what the issue could be?

**Comment by adamisntdead** [comment]
Hello! I actually know exactly what that is - When I published the code to Pypi yesterday, I forgot to push the core QCGPU package also, so It calls a function that's not there yet.

I will try to fix it in the next few minutes

**Comment by adamisntdead** [comment]
Will you try that again? Upgrade the 'qcgpu' package to 0.0.5.

**Comment by BetaByter** [comment]
That did it! Thank you for the quick fix.
