### ISSUE TITLE
suggestion for test for state vector

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-qcgpu-provider#5]
I would not test the state vector to the absolute values of each term. In quantum global phase does not matter. We made in qiskit a state_fedility which you could use and if it is equal to one then it is the same state. 

I know this does not matter too much for now but I could imagine you optimizing for global phase at some point. 

It could also be good to have a test that compares the outcomes of random circuits from BasicAer and your statevector simulator.

**Comment by adamisntdead** [comment]
Good idea, I will look at that

**Comment by adamisntdead** [comment]
This was implemented, closing.
